/**
 * Seed data for UAE area name mapping.
 *
 * Contains ~150 canonical area names for Dubai and Abu Dhabi with known aliases.
 * Used to initialize the area_names table for normalization.
 */

export interface AreaSeed {
  canonicalName: string;
  emirate: "dubai" | "abu_dhabi";
  aliases?: string[];
  sourceVariants?: string[];
}

/**
 * Seed areas for Dubai (~100 areas) and Abu Dhabi (~50 areas).
 * Covers major residential, commercial, and mixed-use districts.
 */
export const SEED_AREAS: AreaSeed[] = [
  // ── Dubai Areas (alphabetical) ────────────────────────────────────────────
  { canonicalName: "Al Barsha", emirate: "dubai", aliases: ["Al Barsha 1", "Al Barsha 2", "Al Barsha 3"], sourceVariants: ["AL BARSHA"] },
  { canonicalName: "Al Furjan", emirate: "dubai", sourceVariants: ["AL FURJAN"] },
  { canonicalName: "Al Mamzar", emirate: "dubai", sourceVariants: ["AL MAMZAR"] },
  { canonicalName: "Al Nahda", emirate: "dubai", aliases: ["Al Nahda 1", "Al Nahda 2"], sourceVariants: ["AL NAHDA"] },
  { canonicalName: "Al Quoz", emirate: "dubai", aliases: ["Al Quoz 1", "Al Quoz 2", "Al Quoz 3", "Al Quoz 4"], sourceVariants: ["AL QUOZ"] },
  { canonicalName: "Al Rashidiya", emirate: "dubai", sourceVariants: ["AL RASHIDIYA"] },
  { canonicalName: "Al Wasl", emirate: "dubai", sourceVariants: ["AL WASL"] },
  { canonicalName: "Al Warqa", emirate: "dubai", aliases: ["Al Warqa 1", "Al Warqa 2", "Al Warqa 3"], sourceVariants: ["AL WARQA"] },
  { canonicalName: "Arabian Ranches", emirate: "dubai", aliases: ["Arabian Ranches 1", "Arabian Ranches 2", "Arabian Ranches 3"], sourceVariants: ["ARABIAN RANCHES"] },
  { canonicalName: "Bluewaters Island", emirate: "dubai", aliases: ["Bluewaters"], sourceVariants: ["BLUEWATERS ISLAND"] },
  { canonicalName: "Bur Dubai", emirate: "dubai", sourceVariants: ["BUR DUBAI"] },
  { canonicalName: "Business Bay", emirate: "dubai", sourceVariants: ["BUSINESS BAY"] },
  { canonicalName: "City Walk", emirate: "dubai", sourceVariants: ["CITY WALK"] },
  { canonicalName: "Damac Hills", emirate: "dubai", aliases: ["Akoya"], sourceVariants: ["DAMAC HILLS", "AKOYA"] },
  { canonicalName: "Damac Hills 2", emirate: "dubai", aliases: ["Akoya Oxygen"], sourceVariants: ["DAMAC HILLS 2", "AKOYA OXYGEN"] },
  { canonicalName: "Deira", emirate: "dubai", sourceVariants: ["DEIRA"] },
  { canonicalName: "DIFC", emirate: "dubai", aliases: ["Dubai International Financial Centre"], sourceVariants: ["DIFC"] },
  { canonicalName: "Discovery Gardens", emirate: "dubai", sourceVariants: ["DISCOVERY GARDENS"] },
  { canonicalName: "Downtown Dubai", emirate: "dubai", sourceVariants: ["DOWNTOWN DUBAI"] },
  { canonicalName: "Dubai Creek Beach", emirate: "dubai", sourceVariants: ["DUBAI CREEK BEACH"] },
  { canonicalName: "Dubai Creek Harbour", emirate: "dubai", aliases: ["DCH"], sourceVariants: ["DUBAI CREEK HARBOUR"] },
  { canonicalName: "Dubai Festival City", emirate: "dubai", aliases: ["DFC"], sourceVariants: ["DUBAI FESTIVAL CITY"] },
  { canonicalName: "Dubai Harbour", emirate: "dubai", sourceVariants: ["DUBAI HARBOUR"] },
  { canonicalName: "Dubai Hills Estate", emirate: "dubai", aliases: ["Dubai Hills"], sourceVariants: ["DUBAI HILLS ESTATE"] },
  { canonicalName: "Dubai Investment Park", emirate: "dubai", aliases: ["DIP"], sourceVariants: ["DUBAI INVESTMENT PARK", "DIP"] },
  { canonicalName: "Dubai Land", emirate: "dubai", aliases: ["Dubailand"], sourceVariants: ["DUBAI LAND", "DUBAILAND"] },
  { canonicalName: "Dubai Marina", emirate: "dubai", sourceVariants: ["DUBAI MARINA"] },
  { canonicalName: "Dubai Maritime City", emirate: "dubai", sourceVariants: ["DUBAI MARITIME CITY"] },
  { canonicalName: "Dubai Production City", emirate: "dubai", aliases: ["IMPZ"], sourceVariants: ["DUBAI PRODUCTION CITY", "IMPZ"] },
  { canonicalName: "Dubai Silicon Oasis", emirate: "dubai", aliases: ["DSO"], sourceVariants: ["DUBAI SILICON OASIS", "DSO"] },
  { canonicalName: "Dubai South", emirate: "dubai", aliases: ["Dubai World Central"], sourceVariants: ["DUBAI SOUTH"] },
  { canonicalName: "Dubai Sports City", emirate: "dubai", aliases: ["Sports City"], sourceVariants: ["DUBAI SPORTS CITY", "SPORTS CITY"] },
  { canonicalName: "Emaar Beachfront", emirate: "dubai", sourceVariants: ["EMAAR BEACHFRONT"] },
  { canonicalName: "Emirates Hills", emirate: "dubai", sourceVariants: ["EMIRATES HILLS"] },
  { canonicalName: "Emirates Living", emirate: "dubai", sourceVariants: ["EMIRATES LIVING"] },
  { canonicalName: "Expo City Dubai", emirate: "dubai", aliases: ["Expo 2020"], sourceVariants: ["EXPO CITY DUBAI"] },
  { canonicalName: "International City", emirate: "dubai", sourceVariants: ["INTERNATIONAL CITY"] },
  { canonicalName: "Jebel Ali", emirate: "dubai", sourceVariants: ["JEBEL ALI"] },
  { canonicalName: "Jumeirah", emirate: "dubai", aliases: ["Jumeirah 1", "Jumeirah 2", "Jumeirah 3"], sourceVariants: ["JUMEIRAH"] },
  { canonicalName: "Jumeirah Beach Residence", emirate: "dubai", aliases: ["JBR"], sourceVariants: ["JUMEIRAH BEACH RESIDENCE", "JBR"] },
  { canonicalName: "Jumeirah Golf Estates", emirate: "dubai", aliases: ["JGE"], sourceVariants: ["JUMEIRAH GOLF ESTATES"] },
  { canonicalName: "Jumeirah Islands", emirate: "dubai", sourceVariants: ["JUMEIRAH ISLANDS"] },
  { canonicalName: "Jumeirah Lake Towers", emirate: "dubai", aliases: ["JLT"], sourceVariants: ["JUMEIRAH LAKE TOWERS", "JLT"] },
  { canonicalName: "Jumeirah Park", emirate: "dubai", sourceVariants: ["JUMEIRAH PARK"] },
  { canonicalName: "Jumeirah Village Circle", emirate: "dubai", aliases: ["JVC"], sourceVariants: ["JUMEIRAH VILLAGE CIRCLE", "JVC"] },
  { canonicalName: "Jumeirah Village Triangle", emirate: "dubai", aliases: ["JVT"], sourceVariants: ["JUMEIRAH VILLAGE TRIANGLE", "JVT"] },
  { canonicalName: "Karama", emirate: "dubai", sourceVariants: ["KARAMA"] },
  { canonicalName: "La Mer", emirate: "dubai", sourceVariants: ["LA MER"] },
  { canonicalName: "Madinat Jumeirah Living", emirate: "dubai", aliases: ["MJL"], sourceVariants: ["MADINAT JUMEIRAH LIVING"] },
  { canonicalName: "Meydan", emirate: "dubai", aliases: ["Meydan City"], sourceVariants: ["MEYDAN"] },
  { canonicalName: "Mirdif", emirate: "dubai", sourceVariants: ["MIRDIF"] },
  { canonicalName: "Mohammed Bin Rashid City", emirate: "dubai", aliases: ["MBR City"], sourceVariants: ["MOHAMMED BIN RASHID CITY", "MBR CITY"] },
  { canonicalName: "Motor City", emirate: "dubai", sourceVariants: ["MOTOR CITY"] },
  { canonicalName: "Mudon", emirate: "dubai", sourceVariants: ["MUDON"] },
  { canonicalName: "Palm Jumeirah", emirate: "dubai", aliases: ["The Palm"], sourceVariants: ["PALM JUMEIRAH"] },
  { canonicalName: "Port de La Mer", emirate: "dubai", sourceVariants: ["PORT DE LA MER"] },
  { canonicalName: "Ras Al Khor", emirate: "dubai", sourceVariants: ["RAS AL KHOR"] },
  { canonicalName: "Remraam", emirate: "dubai", sourceVariants: ["REMRAAM"] },
  { canonicalName: "Satwa", emirate: "dubai", sourceVariants: ["SATWA"] },
  { canonicalName: "The Greens", emirate: "dubai", sourceVariants: ["THE GREENS"] },
  { canonicalName: "The Lakes", emirate: "dubai", sourceVariants: ["THE LAKES"] },
  { canonicalName: "The Meadows", emirate: "dubai", sourceVariants: ["THE MEADOWS"] },
  { canonicalName: "The Springs", emirate: "dubai", sourceVariants: ["THE SPRINGS"] },
  { canonicalName: "The Sustainable City", emirate: "dubai", sourceVariants: ["THE SUSTAINABLE CITY"] },
  { canonicalName: "The Valley", emirate: "dubai", sourceVariants: ["THE VALLEY"] },
  { canonicalName: "The Views", emirate: "dubai", sourceVariants: ["THE VIEWS"] },
  { canonicalName: "The World Islands", emirate: "dubai", aliases: ["The World"], sourceVariants: ["THE WORLD ISLANDS"] },
  { canonicalName: "Tilal Al Ghaf", emirate: "dubai", sourceVariants: ["TILAL AL GHAF"] },
  { canonicalName: "Town Square", emirate: "dubai", sourceVariants: ["TOWN SQUARE"] },
  { canonicalName: "Umm Suqeim", emirate: "dubai", aliases: ["Umm Suqeim 1", "Umm Suqeim 2", "Umm Suqeim 3"], sourceVariants: ["UMM SUQEIM"] },
  { canonicalName: "Villanova", emirate: "dubai", sourceVariants: ["VILLANOVA"] },
  { canonicalName: "Warsan", emirate: "dubai", aliases: ["Al Warsan"], sourceVariants: ["WARSAN", "AL WARSAN"] },

  // Additional Dubai areas to reach ~100
  { canonicalName: "Academic City", emirate: "dubai", sourceVariants: ["ACADEMIC CITY"] },
  { canonicalName: "Al Barari", emirate: "dubai", sourceVariants: ["AL BARARI"] },
  { canonicalName: "Al Jaddaf", emirate: "dubai", sourceVariants: ["AL JADDAF"] },
  { canonicalName: "Al Khail Heights", emirate: "dubai", sourceVariants: ["AL KHAIL HEIGHTS"] },
  { canonicalName: "Al Mizhar", emirate: "dubai", sourceVariants: ["AL MIZHAR"] },
  { canonicalName: "Al Qusais", emirate: "dubai", sourceVariants: ["AL QUSAIS"] },
  { canonicalName: "Al Safa", emirate: "dubai", sourceVariants: ["AL SAFA"] },
  { canonicalName: "Al Sufouh", emirate: "dubai", sourceVariants: ["AL SUFOUH"] },
  { canonicalName: "Al Twar", emirate: "dubai", sourceVariants: ["AL TWAR"] },
  { canonicalName: "Arjan", emirate: "dubai", sourceVariants: ["ARJAN"] },
  { canonicalName: "Barsha Heights", emirate: "dubai", aliases: ["TECOM"], sourceVariants: ["BARSHA HEIGHTS", "TECOM"] },
  { canonicalName: "Creek Villas", emirate: "dubai", sourceVariants: ["CREEK VILLAS"] },
  { canonicalName: "Culture Village", emirate: "dubai", aliases: ["Al Jaddaf Waterfront"], sourceVariants: ["CULTURE VILLAGE"] },
  { canonicalName: "Dubai Design District", emirate: "dubai", aliases: ["D3"], sourceVariants: ["DUBAI DESIGN DISTRICT", "D3"] },
  { canonicalName: "Dubai Healthcare City", emirate: "dubai", aliases: ["DHCC"], sourceVariants: ["DUBAI HEALTHCARE CITY"] },
  { canonicalName: "Dubai Internet City", emirate: "dubai", aliases: ["DIC"], sourceVariants: ["DUBAI INTERNET CITY"] },
  { canonicalName: "Dubai Media City", emirate: "dubai", aliases: ["DMC"], sourceVariants: ["DUBAI MEDIA CITY"] },
  { canonicalName: "Dubai Studio City", emirate: "dubai", sourceVariants: ["DUBAI STUDIO CITY"] },
  { canonicalName: "Green Community", emirate: "dubai", aliases: ["Green Community East", "Green Community West"], sourceVariants: ["GREEN COMMUNITY"] },
  { canonicalName: "Liwan", emirate: "dubai", sourceVariants: ["LIWAN"] },
  { canonicalName: "Living Legends", emirate: "dubai", sourceVariants: ["LIVING LEGENDS"] },
  { canonicalName: "Nad Al Sheba", emirate: "dubai", sourceVariants: ["NAD AL SHEBA"] },
  { canonicalName: "Palm Jebel Ali", emirate: "dubai", sourceVariants: ["PALM JEBEL ALI"] },
  { canonicalName: "Reem", emirate: "dubai", sourceVariants: ["REEM"] },
  { canonicalName: "Serena", emirate: "dubai", sourceVariants: ["SERENA"] },
  { canonicalName: "The Hills", emirate: "dubai", sourceVariants: ["THE HILLS"] },
  { canonicalName: "The Lagoons", emirate: "dubai", sourceVariants: ["THE LAGOONS"] },
  { canonicalName: "The Villa", emirate: "dubai", sourceVariants: ["THE VILLA"] },
  { canonicalName: "Victory Heights", emirate: "dubai", sourceVariants: ["VICTORY HEIGHTS"] },
  { canonicalName: "Wasl Gate", emirate: "dubai", sourceVariants: ["WASL GATE"] },

  // ── Abu Dhabi Areas (alphabetical) ────────────────────────────────────────
  { canonicalName: "Al Bateen", emirate: "abu_dhabi", sourceVariants: ["AL BATEEN"] },
  { canonicalName: "Al Falah", emirate: "abu_dhabi", sourceVariants: ["AL FALAH"] },
  { canonicalName: "Al Ghadeer", emirate: "abu_dhabi", sourceVariants: ["AL GHADEER"] },
  { canonicalName: "Al Khalidiyah", emirate: "abu_dhabi", sourceVariants: ["AL KHALIDIYAH"] },
  { canonicalName: "Al Manhal", emirate: "abu_dhabi", sourceVariants: ["AL MANHAL"] },
  { canonicalName: "Al Maryah Island", emirate: "abu_dhabi", sourceVariants: ["AL MARYAH ISLAND"] },
  { canonicalName: "Al Muroor", emirate: "abu_dhabi", sourceVariants: ["AL MUROOR"] },
  { canonicalName: "Al Mushrif", emirate: "abu_dhabi", sourceVariants: ["AL MUSHRIF"] },
  { canonicalName: "Al Nahyan", emirate: "abu_dhabi", sourceVariants: ["AL NAHYAN"] },
  { canonicalName: "Al Raha Beach", emirate: "abu_dhabi", sourceVariants: ["AL RAHA BEACH"] },
  { canonicalName: "Al Reef", emirate: "abu_dhabi", aliases: ["Al Reef Villas", "Al Reef Downtown"], sourceVariants: ["AL REEF"] },
  { canonicalName: "Al Reem Island", emirate: "abu_dhabi", sourceVariants: ["AL REEM ISLAND"] },
  { canonicalName: "Al Samha", emirate: "abu_dhabi", sourceVariants: ["AL SAMHA"] },
  { canonicalName: "Al Shamkha", emirate: "abu_dhabi", sourceVariants: ["AL SHAMKHA"] },
  { canonicalName: "Al Shawamekh", emirate: "abu_dhabi", sourceVariants: ["AL SHAWAMEKH"] },
  { canonicalName: "Al Wathba", emirate: "abu_dhabi", sourceVariants: ["AL WATHBA"] },
  { canonicalName: "Bloom Living", emirate: "abu_dhabi", sourceVariants: ["BLOOM LIVING"] },
  { canonicalName: "Corniche Area", emirate: "abu_dhabi", aliases: ["Corniche"], sourceVariants: ["CORNICHE AREA"] },
  { canonicalName: "Electra Street", emirate: "abu_dhabi", sourceVariants: ["ELECTRA STREET"] },
  { canonicalName: "Hamdan Street", emirate: "abu_dhabi", sourceVariants: ["HAMDAN STREET"] },
  { canonicalName: "Hydra Village", emirate: "abu_dhabi", sourceVariants: ["HYDRA VILLAGE"] },
  { canonicalName: "Khalifa City", emirate: "abu_dhabi", aliases: ["Khalifa City A", "Khalifa City B"], sourceVariants: ["KHALIFA CITY"] },
  { canonicalName: "Masdar City", emirate: "abu_dhabi", sourceVariants: ["MASDAR CITY"] },
  { canonicalName: "Mohammed Bin Zayed City", emirate: "abu_dhabi", aliases: ["MBZ City"], sourceVariants: ["MOHAMMED BIN ZAYED CITY", "MBZ CITY"] },
  { canonicalName: "Saadiyat Island", emirate: "abu_dhabi", sourceVariants: ["SAADIYAT ISLAND"] },
  { canonicalName: "Tourist Club Area", emirate: "abu_dhabi", aliases: ["TCA"], sourceVariants: ["TOURIST CLUB AREA", "TCA"] },
  { canonicalName: "Yas Island", emirate: "abu_dhabi", sourceVariants: ["YAS ISLAND"] },
  { canonicalName: "Zayed City", emirate: "abu_dhabi", sourceVariants: ["ZAYED CITY"] },

  // Additional Abu Dhabi areas to reach ~50
  { canonicalName: "Abu Dhabi Gate City", emirate: "abu_dhabi", sourceVariants: ["ABU DHABI GATE CITY"] },
  { canonicalName: "Al Bandar", emirate: "abu_dhabi", sourceVariants: ["AL BANDAR"] },
  { canonicalName: "Al Dhafra", emirate: "abu_dhabi", sourceVariants: ["AL DHAFRA"] },
  { canonicalName: "Al Forsan Village", emirate: "abu_dhabi", sourceVariants: ["AL FORSAN VILLAGE"] },
  { canonicalName: "Al Hudayriat Island", emirate: "abu_dhabi", sourceVariants: ["AL HUDAYRIAT ISLAND"] },
  { canonicalName: "Al Karamah", emirate: "abu_dhabi", sourceVariants: ["AL KARAMAH"] },
  { canonicalName: "Al Maqtaa", emirate: "abu_dhabi", sourceVariants: ["AL MAQTAA"] },
  { canonicalName: "Al Rahba", emirate: "abu_dhabi", sourceVariants: ["AL RAHBA"] },
  { canonicalName: "Al Raha Gardens", emirate: "abu_dhabi", sourceVariants: ["AL RAHA GARDENS"] },
  { canonicalName: "Al Rowdah", emirate: "abu_dhabi", sourceVariants: ["AL ROWDAH"] },
  { canonicalName: "Al Wahda", emirate: "abu_dhabi", sourceVariants: ["AL WAHDA"] },
  { canonicalName: "Al Zaab", emirate: "abu_dhabi", sourceVariants: ["AL ZAAB"] },
  { canonicalName: "Al Zahiyah", emirate: "abu_dhabi", sourceVariants: ["AL ZAHIYAH"] },
  { canonicalName: "Al Zeina", emirate: "abu_dhabi", sourceVariants: ["AL ZEINA"] },
  { canonicalName: "Baniyas", emirate: "abu_dhabi", sourceVariants: ["BANIYAS"] },
  { canonicalName: "Capital Centre", emirate: "abu_dhabi", sourceVariants: ["CAPITAL CENTRE"] },
  { canonicalName: "Danet Abu Dhabi", emirate: "abu_dhabi", sourceVariants: ["DANET ABU DHABI"] },
  { canonicalName: "Eastern Mangroves", emirate: "abu_dhabi", sourceVariants: ["EASTERN MANGROVES"] },
  { canonicalName: "Hadbat Al Zaafaran", emirate: "abu_dhabi", sourceVariants: ["HADBAT AL ZAAFARAN"] },
  { canonicalName: "Khalifa Park", emirate: "abu_dhabi", sourceVariants: ["KHALIFA PARK"] },
  { canonicalName: "Mussafah", emirate: "abu_dhabi", sourceVariants: ["MUSSAFAH"] },
  { canonicalName: "Shakhbout City", emirate: "abu_dhabi", sourceVariants: ["SHAKHBOUT CITY"] },
  { canonicalName: "Sas Al Nakhl", emirate: "abu_dhabi", sourceVariants: ["SAS AL NAKHL"] },
];
